on: push
name: CI
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools setuptools_scm wheel
          sudo apt-get install flex bison ccache cmake libboost-program-options-dev libboost-filesystem-dev libboost-system-dev
      - name: Set up ccache
        uses: actions/cache@v1
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-
      - name: Build WASM binaries
        run: |
          ./build.sh
      - name: Build binary wheels
        run: |
          cd pypi
          python setup.py bdist_wheel
          rm -rf build && DEVICE=384 python setup.py bdist_wheel
          rm -rf build && DEVICE=1k python setup.py bdist_wheel
          rm -rf build && DEVICE=5k python setup.py bdist_wheel
          rm -rf build && DEVICE=8k python setup.py bdist_wheel
          rm -rf build && DEVICE=u4k python setup.py bdist_wheel
          rm -rf build && DEVICE=384,1k,5k,8k,u4k python setup.py bdist_wheel
          sha256sum dist/*.whl
      - name: Upload binary wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: pypi/dist/
      - name: Test binary wheels
        run: |
          pip install pypi/dist/*.whl
          yowasp-icepll --help || true
          yowasp-icebram --help || true
          yowasp-icemulti --help || true
          yowasp-icepack --help || true
          yowasp-iceunpack --help || true
          yowasp-nextpnr-ice40 --help
          yowasp-nextpnr-ice40 --test
  upload_wheels:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: wheel
        path: dist/
    - name: Publish wheels to Test PyPI
      if: github.event_name == 'push' && github.event.ref == 'refs/heads/develop'
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.test_pypi_token }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish wheels to PyPI
      if: github.event_name == 'push' && github.event.ref == 'refs/heads/release'
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
